### ISSUE TITLE
CSS3 Hacks - New type of hack!

### ISSUE THREAD

**Issue by jeffclayton** [4ae9b8/browserhacks#150]
Firefox 31 is the first browser to support CSS3 Variables, which gives opportunity for a new type of hack. So here are my first CSS hacks using them.

Just make sure that you use a different variable in each definition.
They really are variables, not constants, so they can override each other.

``` css
/* Firefox 31+ (CSS3 Variable Method) */
_:-moz-tree-row(hover), .selector {
    --this-variable:value; property:var(--this-variable);
}
```

And using a supports method…

``` css
/* Firefox 31+ (CSS3 Variable Method) */
@supports (-moz-appearance:meterbar) {
    .selector {
       --this-variable:value; property:var(--this-variable);
    }
}
```

Other browsers are supposed to follow suit, but for now just Firefox 31 and newer.
