### ISSUE TITLE
Safari (version?) and Chrome (not Canary)

### ISSUE THREAD

**Issue by xzyfer** [4ae9b8/browserhacks#65]
``` css
/* Safari (version?) and Chrome (not Canary) */
::made-up-pseudo-element, .selector { background: lightgreen; }
```

This works on Safari 6.0.2, iOS 6, and Chrome and iOS. But not Chrome 26 desktop.

![Screen Shot 2013-04-21 at 12 17 05 PM](https://f.cloud.github.com/assets/579928/405935/b473a476-aa29-11e2-826f-deffe4a958ff.png)
