### ISSUE TITLE
Selector Hack is working in IE10 too

### ISSUE THREAD

**Issue by FWeinb** [4ae9b8/browserhacks#73]
This selector hack is working in IE10:

``` css
@media all and (min-width: 0px){ .selector { background: lightgreen; } }
```

On the page there is only: Opera 7/15 and Chrome \* listed.
